# Generated by TradeForge v0.1.0
# Service: fx-rates-pipeline | Domain: fx | Env: staging
# REGENERATE: tradeforge scaffold --type notebooks --config service.yaml

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from datetime import date
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("fx-rates-pipeline")

spark = SparkSession.builder \
    .appName("fx-rates-pipeline-ingestion") \
    .config("spark.sql.adaptive.enabled", "true") \
    .getOrCreate()


def assert_quality(df, checkpoint_name: str, min_rows: int = 1):
    """
    SOX-compliant quality checkpoint.
    Every checkpoint is logged for audit trail.
    Fails the pipeline — not silently continues — on bad data.
    """
    count = df.count()
    logger.info(f"[QUALITY] {checkpoint_name}: {count} rows")
    assert count >= min_rows, (
        f"[QUALITY GATE FAILED] {checkpoint_name}: "
        f"got {count} rows, expected >= {min_rows}. Pipeline halted."
    )
    return df


# ── INGESTION ─────────────────────────────────────────────────────
raw_df = spark.read \
    .format("json") \
    .option("multiLine", True) \
    .load("s3://fx-rates-pipeline-data-lake-staging/raw/fx/bloomberg_api/")

raw_df = assert_quality(raw_df, "raw_ingestion")

# ── TRANSFORMATION ────────────────────────────────────────────────
transformed_df = raw_df \
    .withColumn("ingestion_ts", F.current_timestamp()) \
    .withColumn("pipeline_version", F.lit("0.1.0")) \
    .withColumn("data_classification", F.lit("confidential")) \
    .withColumn("ingestion_date", F.to_date(F.current_timestamp()))

# ── PII MASKING ───────────────────────────────────────────────────

transformed_df = assert_quality(transformed_df, "post_transform")

# ── WRITE ─────────────────────────────────────────────────────────
transformed_df.write \
    .mode("append") \
    .partitionBy("ingestion_date") \
    .parquet("s3://fx-rates-pipeline-data-lake-staging/processed/fx/fx-rates-pipeline/")

logger.info(f"Pipeline complete. Rows written: {transformed_df.count()}")