"""Atlassian generator — creates Jira epic + stories and Confluence ADR."""

from __future__ import annotations

import os
import time
import base64
from pathlib import Path

import requests
from dotenv import load_dotenv
from datetime import datetime, timezone
from jinja2 import Environment, FileSystemLoader, StrictUndefined

load_dotenv()


def _adf(text: str) -> dict:
    """Minimal Atlassian Document Format wrapper for plain text."""
    return {
        "type": "doc",
        "version": 1,
        "content": [
            {
                "type": "paragraph",
                "content": [{"type": "text", "text": text}],
            }
        ],
    }


class JiraClient:
    def __init__(self) -> None:
        base_url = os.environ["ATLASSIAN_BASE_URL"].rstrip("/")
        email = os.environ["ATLASSIAN_EMAIL"]
        token = os.environ["ATLASSIAN_API_TOKEN"]

        token_b64 = base64.b64encode(f"{email}:{token}".encode()).decode()
        self.base_url = base_url
        self.headers = {
            "Authorization": f"Basic {token_b64}",
            "Content-Type": "application/json",
            "Accept": "application/json",
        }

    def _post(self, endpoint: str, payload: dict) -> dict:
        url = f"{self.base_url}/rest/api/3/{endpoint}"
        resp = requests.post(url, headers=self.headers, json=payload, timeout=10)
        if not resp.ok:
            print(f"[DEBUG] Status: {resp.status_code}")
            print(f"[DEBUG] Body: {resp.text}")
        resp.raise_for_status()
        time.sleep(0.1)
        return resp.json()

    def find_issue(self, project_key: str, summary: str, issue_type: str) -> str | None:
        jql = f'project = "{project_key}" AND issuetype = "{issue_type}" AND summary ~ "\\"{summary}\\""'
        url = f"{self.base_url}/rest/api/3/search/jql"   # ← updated endpoint
        resp = requests.get(
            url,
            headers=self.headers,
            params={"jql": jql, "maxResults": 1, "fields": "summary"},
            timeout=10,
        )
        resp.raise_for_status()
        issues = resp.json().get("issues", [])
        return issues[0]["key"] if issues else None

    def create_epic(self, project_key: str, epic_name: str, domain: str) -> tuple[str, bool]:
        """Create epic if it doesn't exist. Returns (key, created)."""
        existing = self.find_issue(project_key, epic_name, "Epic")
        if existing:
            return existing, False

        payload = {
            "fields": {
                "project": {"key": project_key},
                "summary": epic_name,
                "description": _adf(
                    f"Auto-generated by TradeForge scaffold for domain: {domain}. "
                    f"This epic tracks all delivery work for the {epic_name} initiative."
                ),
                "issuetype": {"name": "Epic"},
            }
        }
        result = self._post("issue", payload)
        return result["key"], True

    def create_story(
        self, project_key: str, epic_key: str, summary: str, description: str
    ) -> str:
        payload = {
            "fields": {
                "project": {"key": project_key},
                "summary": summary,
                "description": _adf(description),
                "issuetype": {"name": "Story"},
                "parent": {"key": epic_key},
            }
        }
        result = self._post("issue", payload)
        return str(result["key"])


class ConfluenceClient:
    def __init__(self) -> None:
        base_url = os.environ["ATLASSIAN_BASE_URL"].rstrip("/")
        email = os.environ["ATLASSIAN_EMAIL"]
        token = os.environ["ATLASSIAN_API_TOKEN"]

        token_b64 = base64.b64encode(f"{email}:{token}".encode()).decode()
        self.base_url = base_url
        self.headers = {
            "Authorization": f"Basic {token_b64}",
            "Content-Type": "application/json",
            "Accept": "application/json",
        }

    def _post(self, endpoint: str, payload: dict) -> dict:
        url = f"{self.base_url}/wiki/api/v2/{endpoint}"
        resp = requests.post(url, headers=self.headers, json=payload, timeout=10)
        if not resp.ok:
            print(f"[DEBUG] Confluence {resp.status_code}: {resp.text}")
        resp.raise_for_status()
        return resp.json()

    def get_space_id(self, space_key: str) -> str:
        """Resolve space key to numeric space ID (returned as string for JSON compat)."""
        url = f"{self.base_url}/wiki/api/v2/spaces"
        resp = requests.get(
            url,
            headers=self.headers,
            params={"keys": space_key},
            timeout=10,
        )
        resp.raise_for_status()
        results = resp.json().get("results", [])
        if not results:
            raise ValueError(f"Confluence space '{space_key}' not found.")
        return str(results[0]["id"])

    def create_page(self, space_id: str, title: str, body_html: str) -> str:
        """Create a page, return its URL."""
        payload = {
            "spaceId": space_id,
            "status": "current",
            "title": title,
            "body": {
                "representation": "storage",
                "value": body_html,
            },
        }
        result = self._post("pages", payload)
        page_id = result["id"]
        return f"{self.base_url}/wiki/spaces/{result.get('spaceKey', '')}/pages/{page_id}"


STANDARD_STORIES = [
    (
        "Infra: Provision AWS resources",
        "Run terraform init and apply for VPC, S3, and IAM role. Validate state file is stored remotely.",
    ),
    (
        "CI/CD: Configure GitHub Actions pipeline",
        "Verify lint, compliance-scan, and deploy jobs are wired. SOX gate must block on CRITICAL findings.",
    ),
    (
        "Data: Implement ingestion notebook",
        "PySpark ingestion with assert_quality() checkpoint. DQ failures must raise, not warn.",
    ),
    (
        "Compliance: Run TradeForge compliance scanner",
        "Zero CRITICAL findings required before merge. SARIF report uploaded to GitHub Code Scanning.",
    ),
    (
        "Docs: Publish ADR to Confluence",
        "Architecture Decision Record for this service must be approved before production deploy.",
    ),
]

DOMAIN_STORIES: dict[str, list[tuple[str, str]]] = {
    "fx": [
        (
            "FX: Bloomberg API rate ingestion",
            "Implement Bloomberg B-PIPE polling. Handle DELAYED vs REALTIME entitlements.",
        ),
        (
            "FX: Cross-rate derivation (EUR/INR via USD)",
            "Derived rates must be audit-logged. Formula: EUR/INR = EUR/USD × USD/INR.",
        ),
    ],
    "payments": [
        (
            "UPI: DEEMED state reconciliation",
            "Three-cohort logic per RBI circular. Cohort C must generate exception report within T+1.",
        ),
        (
            "UPI: VPA masking in all log statements",
            "VPA (virtual payment address) must be masked as ***@bank before any logger call.",
        ),
        (
            "UPI: NPCI settlement file parser",
            "Load .txt settlement file from S3. Validate column schema before join.",
        ),
    ],
}


def run_atlassian(spec) -> None:
    from rich.console import Console

    console = Console()

    cfg = spec.atlassian
    if not cfg:
        console.print("[yellow]No atlassian config in spec — skipping.[/yellow]")
        return

    missing = [
        v
        for v in ("ATLASSIAN_BASE_URL", "ATLASSIAN_EMAIL", "ATLASSIAN_API_TOKEN")
        if not os.environ.get(v)
    ]
    if missing:
        console.print(f"[yellow]⚠ Missing env vars: {missing} — skipping Atlassian.[/yellow]")
        return

    try:
        client = JiraClient()
        _run_jira(client, cfg, spec, console)
    except requests.HTTPError as e:
        console.print(
            f"[red]✗ Jira API error ({e.response.status_code}): {e.response.text[:200]}[/red]"
        )
        console.print("[dim]Tip: verify Jira is enabled at admin.atlassian.com → Products[/dim]")
    except requests.ConnectionError:
        console.print("[red]✗ Cannot reach Atlassian — check ATLASSIAN_BASE_URL in .env[/red]")


def _run_jira(client: JiraClient, cfg, spec, console) -> None:
    """Inner function — called only when connectivity is confirmed."""
    console.print(f"[cyan]Creating Jira epic: {cfg.epic_name}[/cyan]")

    epic_key, created = client.create_epic(
        cfg.jira_project_key, cfg.epic_name, spec.service.domain
    )

    if created:
        console.print(f"  [green]✓ Epic created: {epic_key}[/green]")
        all_stories = STANDARD_STORIES + DOMAIN_STORIES.get(spec.service.domain, [])
        for summary, description in all_stories:
            story_key = client.create_story(cfg.jira_project_key, epic_key, summary, description)
            console.print(f"  [green]✓ Story: {story_key} — {summary}[/green]")
        console.print(f"\n[bold green]Jira: {len(all_stories)} stories created under {epic_key}[/bold green]")
    else:
        console.print(f"  [yellow]↩ Epic already exists: {epic_key} — skipping stories[/yellow]")

    # Confluence ADR — best effort, does not block on failure
    try:
        confluence = ConfluenceClient()
        adr_url = create_adr(spec, confluence, cfg.confluence_space, epic_key)
        console.print(f"\n[green]✓ ADR published: {adr_url}[/green]")
    except Exception as e:
        console.print(f"[yellow]⚠ Confluence ADR skipped: {e}[/yellow]")


def create_adr(
    spec, confluence_client: ConfluenceClient, space_key: str, epic_key: str
) -> str:
    """Render ADR template and publish to Confluence. Returns page URL."""
    templates_dir = Path(__file__).parent.parent / "templates" / "confluence"
    env = Environment(
        loader=FileSystemLoader(str(templates_dir)),
        undefined=StrictUndefined,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    template = env.get_template("adr.html.j2")

    body_html = template.render(
        service_name=spec.service.name,
        domain=spec.service.domain,
        env=spec.service.env,
        owner=spec.service.owner,
        region=spec.infrastructure.region if spec.infrastructure else "ap-south-1",
        pipeline_type=spec.pipeline.type if spec.pipeline else "batch",
        source=spec.pipeline.source if spec.pipeline else "unknown",
        destination=spec.pipeline.destination if spec.pipeline else "unknown",
        sox_relevant=spec.compliance.sox_relevant,
        pci_dss=spec.compliance.pci_dss,
        data_classification=spec.compliance.data_classification,
        pii_fields=spec.compliance.pii_fields or [],
        epic_key=epic_key,
        timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
    )

    space_id = confluence_client.get_space_id(space_key)
    title = f"ADR: {spec.service.name}"
    return confluence_client.create_page(space_id, title, body_html)