from __future__ import annotations
from pathlib import Path
from datetime import datetime
from config import ServiceSpec

MAIN_TF = """\
# AUTO-GENERATED by TradeForge — do not edit manually
# Service: {service_name} | Domain: {domain} | Generated: {generated_at}
# Regenerate: tradeforge scaffold --type terraform --config service.yaml

terraform {{
  required_version = ">= 1.5"
  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}

  backend "s3" {{
    bucket  = "tradeforge-tfstate-{env}"
    key     = "{service_name}/terraform.tfstate"
    region  = "{region}"
    encrypt = true
  }}
}}

provider "aws" {{
  region = "{region}"

  default_tags {{
    tags = {{
      Service         = "{service_name}"
      Domain          = "{domain}"
      Environment     = "{env}"
      ManagedBy       = "tradeforge"
      SOXRelevant     = "{sox_relevant}"
      DataClass       = "{data_classification}"
    }}
  }}
}}

module "vpc" {{
  source       = "../../modules/vpc"
  service_name = "{service_name}"
  env          = "{env}"
}}

module "s3_data_lake" {{
  source              = "../../modules/s3_data_lake"
  service_name        = "{service_name}"
  env                 = "{env}"
  kms_enabled         = {kms_enabled}
  sox_relevant        = {sox_relevant_tf}
  data_classification = "{data_classification}"
}}

module "iam_pipeline_role" {{
  source        = "../../modules/iam_pipeline_role"
  service_name  = "{service_name}"
  env           = "{env}"
  s3_bucket_arn = module.s3_data_lake.bucket_arn
  kms_key_arn   = module.s3_data_lake.kms_key_arn
}}
"""


class TerraformGenerator:
    def __init__(self, spec: ServiceSpec, dry_run: bool = False) -> None:
        self.spec = spec
        self.dry_run = dry_run
        self.out = Path(f"terraform/generated/{spec.service_name}")

    def generate(self) -> str:
        content = MAIN_TF.format(
            service_name=self.spec.service_name,
            domain=self.spec.domain,
            env=self.spec.env,
            region=self.spec.region,
            sox_relevant=str(self.spec.compliance.sox_relevant),
            sox_relevant_tf=str(self.spec.compliance.sox_relevant).lower(),
            kms_enabled=str(self.spec.compliance.sox_relevant).lower(),
            data_classification=self.spec.compliance.data_classification,
            generated_at=datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
        )

        if self.dry_run:
            print(f"[dry-run] Would write: {self.out}/main.tf")
            return f"[dry-run] {self.out}"

        self.out.mkdir(parents=True, exist_ok=True)
        (self.out / "main.tf").write_text(content)
        print(f"→ {self.out}/main.tf")
        return str(self.out)