# Generated by TradeForge v0.1.0
# Service: upi-payments-engine | Domain: payments | Env: staging
# REGENERATE: tradeforge scaffold --type notebooks --config service.yaml

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from datetime import date
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("upi-payments-engine")

spark = SparkSession.builder \
    .appName("upi-payments-engine-ingestion") \
    .config("spark.sql.adaptive.enabled", "true") \
    .getOrCreate()


def assert_quality(df, checkpoint_name: str, min_rows: int = 1):
    """
    SOX-compliant quality checkpoint.
    Every checkpoint is logged for audit trail.
    Fails the pipeline — not silently continues — on bad data.
    """
    count = df.count()
    logger.info(f"[QUALITY] {checkpoint_name}: {count} rows")
    assert count >= min_rows, (
        f"[QUALITY GATE FAILED] {checkpoint_name}: "
        f"got {count} rows, expected >= {min_rows}. Pipeline halted."
    )
    return df


# ── INGESTION ─────────────────────────────────────────────────────
raw_df = spark.read \
    .format("json") \
    .option("multiLine", True) \
    .load("s3://upi-payments-engine-data-lake-staging/raw/payments/upi_gateway/")

raw_df = assert_quality(raw_df, "raw_ingestion")

# ── TRANSFORMATION ────────────────────────────────────────────────
transformed_df = raw_df \
    .withColumn("ingestion_ts", F.current_timestamp()) \
    .withColumn("pipeline_version", F.lit("0.1.0")) \
    .withColumn("data_classification", F.lit("restricted")) \
    .withColumn("ingestion_date", F.to_date(F.current_timestamp()))

# ── PII MASKING ───────────────────────────────────────────────────
transformed_df = transformed_df.withColumn(
    "vpa_payer",
    F.concat(F.lit("***"), F.substring(F.col("vpa_payer").cast("string"), -4, 4))
)
transformed_df = transformed_df.withColumn(
    "vpa_payee",
    F.concat(F.lit("***"), F.substring(F.col("vpa_payee").cast("string"), -4, 4))
)

transformed_df = assert_quality(transformed_df, "post_transform")

# ── WRITE ─────────────────────────────────────────────────────────
transformed_df.write \
    .mode("append") \
    .partitionBy("ingestion_date") \
    .parquet("s3://upi-payments-engine-data-lake-staging/processed/payments/upi-payments-engine/")

logger.info(f"Pipeline complete. Rows written: {transformed_df.count()}")